#!/usr/bin/env bash
# Regression tests for scripts/agent-commit-metadata.sh.

set -u

TESTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$TESTS_DIR/.." && pwd)"
SCRIPT="$SKILL_DIR/scripts/agent-commit-metadata.sh"
PASS_COUNT=0
FAIL_COUNT=0

pass() { PASS_COUNT=$((PASS_COUNT + 1)); printf '  PASS %s\n' "$1"; }
fail() { FAIL_COUNT=$((FAIL_COUNT + 1)); printf '  FAIL %s\n' "$1"; }

make_repo() {
  local repo
  repo=$(mktemp -d /tmp/test-agent-metadata.XXXXXX)
  git -C "$repo" init -q -b main
  git -C "$repo" -c core.hooksPath=/dev/null -c user.name=test -c user.email=test@example.com \
    commit -q --allow-empty -m init
  printf '%s' "$repo"
}

write_codex_transcript() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  printf '%s\n' \
    '<!-- Generated by SpecStory, Markdown v2.1.0 -->' \
    '<!-- Codex CLI Session abc (2026-08-27 06:27:27Z) -->' \
    '_**Agent (gpt-5.6-sol 2026-08-27 06:27:38Z)**_' \
    '_**Agent (gpt-5.6-sol 2026-08-27 06:28:38Z)**_' \
    > "$path"
}

write_claude_transcript() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  printf '%s\n' \
    '<!-- Claude Code Session def (2026-08-27 06:27:27Z) -->' \
    '_**Agent (Claude Fable 5 2026-08-27 06:27:38Z)**_' \
    '_**Agent (Claude Opus 5 (1M context) 2026-08-27 06:28:38Z)**_' \
    > "$path"
}

printf '== agent commit metadata ==\n'

repo=$(make_repo)
write_codex_transcript "$repo/.specstory/history/session.md"
mkdir -p "$repo/.claude/plans"
printf '# Plan\n' > "$repo/.claude/plans/plan one.md"
git -C "$repo" add .specstory/history/session.md ".claude/plans/plan one.md"
out=$(cd "$repo" && bash "$SCRIPT" 2>/dev/null)
if printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Codex CLI (gpt-5.6-sol)' && \
   [ "$(printf '%s\n' "$out" | grep -c '^AI-Assisted-By:')" = "1" ] && \
   printf '%s\n' "$out" | grep -Fxq 'Agent-Transcript: .specstory/history/session.md' && \
   printf '%s\n' "$out" | grep -Fxq 'Agent-Plan: .claude/plans/plan one.md'; then
  pass "parse staged Codex transcript, dedupe model, preserve spaced plan path"
else
  fail "parse staged Codex transcript"
fi

json=$(cd "$repo" && bash "$SCRIPT" --format json 2>/dev/null)
if printf '%s' "$json" | grep -Fq '"assistants":["Codex CLI (gpt-5.6-sol)"]'; then
  pass "emit JSON"
else
  fail "emit JSON"
fi
rm -rf "$repo"

repo=$(make_repo)
write_claude_transcript "$repo/.specstory/history/session.md"
git -C "$repo" add .specstory/history/session.md
out=$(cd "$repo" && bash "$SCRIPT" 2>/dev/null)
if [ "$(printf '%s\n' "$out" | grep -c '^AI-Assisted-By:')" = "2" ] && \
   printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Claude Code (Claude Fable 5)' && \
   printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Claude Code (Claude Opus 5 (1M context))'; then
  pass "preserve distinct models from one staged session"
else
  fail "preserve distinct models from one staged session"
fi
rm -rf "$repo"

repo=$(make_repo)
mkdir -p "$repo/.cursor/plans"
printf '# Plan\n' > "$repo/.cursor/plans/p.md"
git -C "$repo" add .cursor/plans/p.md
(cd "$repo" && bash "$SCRIPT" >/dev/null 2>&1)
rc=$?
if [ "$rc" = "4" ]; then pass "require explicit identity without transcript"
else fail "require explicit identity without transcript (got $rc)"; fi

out=$(cd "$repo" && bash "$SCRIPT" --harness Cursor --model claude-4.6 2>/dev/null)
if printf '%s\n' "$out" | grep -Fxq 'AI-Assisted-By: Cursor (claude-4.6)'; then
  pass "explicit Cursor override"
else
  fail "explicit Cursor override"
fi
rm -rf "$repo"

repo=$(make_repo)
git -C "$repo" config core.hooksPath .githooks
(cd "$repo" && bash "$SKILL_DIR/scripts/bootstrap-project.sh" --install-hook --dry-run >/dev/null 2>&1)
rc=$?
if [ "$rc" = "6" ] && [ ! -e "$repo/.pre-commit-config.yaml" ]; then
  pass "bootstrap rejects inactive repo hook before writing files"
else
  fail "bootstrap rejects inactive repo hook before writing files (got $rc)"
fi
rm -rf "$repo"

repo=$(make_repo)
(cd "$repo" && bash "$SCRIPT" >/dev/null 2>&1)
rc=$?
if [ "$rc" = "3" ]; then pass "no staged artifacts → exit 3"
else fail "no staged artifacts → exit 3 (got $rc)"; fi
rm -rf "$repo"

printf 'pass: %d\nfail: %d\n' "$PASS_COUNT" "$FAIL_COUNT"
[ "$FAIL_COUNT" = "0" ]
