#!/usr/bin/env bash
# Regression tests for scripts/find-session.sh.
# Bash 3.2 compatible (stock macOS).

set -u

TESTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$TESTS_DIR/.." && pwd)"
SCRIPT="$SKILL_DIR/scripts/find-session.sh"
BASE="$(mktemp -d /tmp/test-find-session.XXXXXX)"
BASE="$(cd "$BASE" && pwd -P)"
FAKE_HOME="$BASE/home"
PASS_COUNT=0
FAIL_COUNT=0
LAST_RC=0
LAST_OUT=""
LAST_ERR=""
TAB="$(printf '\t')"

trap 'rm -rf "$BASE"' EXIT

printf 'bash-under-test: %s (%s)\n' "$BASH_VERSION" "$BASH"
if [ "$(uname -s)" = "Darwin" ] && [ "${BASH_VERSINFO[0]}" != "3" ]; then
  printf 'error: Darwin compatibility suite must run with /bin/bash 3.x\n' >&2
  exit 1
fi

pass() { PASS_COUNT=$((PASS_COUNT + 1)); printf '  PASS %s\n' "$1"; }
fail() { FAIL_COUNT=$((FAIL_COUNT + 1)); printf '  FAIL %s\n' "$1"; }

assert_true() {
  local name="$1"
  shift
  if "$@"; then pass "$name"; else fail "$name"; fi
}

make_repo() {
  local name="$1" repo="$BASE/$1"
  mkdir -p "$repo"
  git -C "$repo" init -q -b main
  git -C "$repo" -c core.hooksPath=/dev/null \
    -c user.name=test -c user.email=test@example.com \
    commit -q --allow-empty -m init
  printf '%s' "$repo"
}

project_slug() {
  printf '%s' "$1" | sed 's|[^A-Za-z0-9]|-|g'
}

write_jsonl() {
  local repo="$1" uuid="$2" recorded_cwd="${3:-$1}" store_cwd="${4:-$1}" path
  path="$FAKE_HOME/.claude/projects/$(project_slug "$store_cwd")/$uuid.jsonl"
  mkdir -p "$(dirname "$path")"
  python3 - "$path" "$uuid" "$recorded_cwd" <<'PY'
import json
import sys

path, session_id, cwd = sys.argv[1:]
with open(path, "w", encoding="utf-8") as stream:
    stream.write(json.dumps({"type": "user", "sessionId": session_id, "cwd": cwd}) + "\n")
PY
  printf '%s' "$path"
}

write_transcript() {
  local repo="$1" name="$2" uuid="$3" path
  path="$repo/.specstory/history/$name"
  mkdir -p "$(dirname "$path")"
  printf '%s\n' \
    '<!-- Generated by SpecStory, Markdown v2.1.0 -->' \
    '' \
    '# 2026-08-28 08:00:00Z' \
    '' \
    "<!-- Claude Code Session $uuid (2026-08-28 08:00:00Z) -->" \
    '' \
    '_**Agent (Claude Opus 5 2026-08-28 08:00:01Z)**_' \
    > "$path"
  printf '%s' "$path"
}

run_find() {
  local cwd="$1"
  shift
  local out="$BASE/out" err="$BASE/err"
  (cd "$cwd" && HOME="$FAKE_HOME" "$BASH" "$SCRIPT" "$@") >"$out" 2>"$err"
  LAST_RC=$?
  LAST_OUT="$(<"$out")"
  LAST_ERR="$(<"$err")"
}

contains() { printf '%s\n' "$1" | grep -Fq -- "$2"; }
count_candidates() { printf '%s\n' "$1" | grep -c '^candidate[[:space:]]'; }

UUID_A="11111111-1111-4111-8111-111111111111"
UUID_B="22222222-2222-4222-8222-222222222222"
UUID_C="33333333-3333-4333-8333-333333333333"
UUID_D="44444444-4444-4444-8444-444444444444"
UUID_E="55555555-5555-4555-8555-555555555555"
UUID_F="66666666-6666-4666-8666-666666666666"
UUID_G="77777777-7777-4777-8777-777777777777"
UUID_H="88888888-8888-4888-8888-888888888888"
UUID_I="99999999-9999-4999-8999-999999999999"
UUID_J="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
UUID_K="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"

printf '== find-session exact selectors ==\n'

# Same checkout, different branches: artifacts remain path-scoped. Make branch
# A's files newer so --newest leaks across the branch switch, then prove the
# branch-B UUID still resolves exactly.
repo="$(make_repo 'same checkout with spaces')"
git -C "$repo" checkout -q -b feature-a
transcript_a="$(write_transcript "$repo" 'feature-a.md' "$UUID_A")"
jsonl_a="$(write_jsonl "$repo" "$UUID_A")"
git -C "$repo" checkout -q -b feature-b
transcript_b="$(write_transcript "$repo" 'feature-b.md' "$UUID_B")"
jsonl_b="$(write_jsonl "$repo" "$UUID_B")"
sleep 1
touch "$transcript_a" "$jsonl_a"
run_find "$repo" --session-id "$UUID_B"
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" $'confidence\texact' && \
   contains "$LAST_OUT" "specstory_path${TAB}$transcript_b" && \
   contains "$LAST_OUT" "claude_jsonl_path${TAB}$jsonl_b"; then
  pass "exact UUID prevents same-checkout branch mtime leakage"
else
  fail "exact UUID prevents same-checkout branch mtime leakage"
fi
run_find "$repo" --newest
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" $'confidence\theuristic' && \
   contains "$LAST_OUT" "$transcript_a" && contains "$LAST_OUT" "$jsonl_a"; then
  pass "newest compatibility mode remains explicit and heuristic"
else
  fail "newest compatibility mode remains explicit and heuristic"
fi

# Duplicate rendered aliases for one UUID must fail until a path disambiguates.
repo_dup="$(make_repo 'duplicate aliases')"
alias_one="$(write_transcript "$repo_dup" 'alias one.md' "$UUID_C")"
alias_two="$(write_transcript "$repo_dup" 'alias two.md' "$UUID_C")"
write_jsonl "$repo_dup" "$UUID_C" >/dev/null
run_find "$repo_dup" --session-id "$UUID_C"
if [ "$LAST_RC" = "4" ] && contains "$LAST_OUT" $'status\tambiguous' && \
   [ "$(count_candidates "$LAST_OUT")" = "2" ] && contains "$LAST_OUT" "$alias_one" && \
   contains "$LAST_OUT" "$alias_two" && contains "$LAST_ERR" 'retry with --specstory-path'; then
  pass "duplicate UUID reports both candidates and exits 4"
else
  fail "duplicate UUID reports both candidates and exits 4"
fi
mkdir -p "$repo_dup/nested/subdir"
run_find "$repo_dup/nested/subdir" --specstory-path '.specstory/history/alias two.md' --json
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" '"status":"resolved"' && \
   contains "$LAST_OUT" '"confidence":"exact"' && contains "$LAST_OUT" "$alias_two"; then
  pass "git-root-relative spaced path resolves from a subdirectory"
else
  fail "git-root-relative spaced path resolves from a subdirectory"
fi

# SpecStory --local-time-zone uses offsets such as -0700 in the title. The
# bounded prologue structure is stable, but UTC-only title text is not.
repo_local_time="$(make_repo 'local timezone prologue')"
local_time_path="$repo_local_time/.specstory/history/local-time.md"
mkdir -p "$(dirname "$local_time_path")"
printf '%s\n' '<!-- Generated by SpecStory, Markdown v2.1.0 -->' '' \
  '# 2026-08-28 01:00:00 -0700' '' \
  "<!-- Claude Code Session $UUID_D (2026-08-28 01:00:00-0700) -->" '' > "$local_time_path"
run_find "$repo_local_time" --specstory-path '.specstory/history/local-time.md' --format specstory
if [ "$LAST_RC" = "0" ]; then
  pass "real prologue accepts local-time-zone title and marker timestamp"
else
  fail "real prologue accepts local-time-zone title and marker timestamp"
fi

# SpecStory-only TSV resolution needs iconv but must not invoke python3.
no_python_bin="$BASE/no-python-bin"
mkdir -p "$no_python_bin"
cat > "$no_python_bin/python3" <<'SH'
#!/usr/bin/env sh
touch "$NO_PYTHON_MARKER"
exit 99
SH
chmod +x "$no_python_bin/python3"
(cd "$repo_local_time" && \
  NO_PYTHON_MARKER="$BASE/python-was-invoked" PATH="$no_python_bin:$PATH" HOME="$FAKE_HOME" \
  "$BASH" "$SCRIPT" --specstory-path "$local_time_path" --format specstory) \
  >"$BASE/no-python-out" 2>"$BASE/no-python-err"
no_python_rc=$?
(cd "$repo_local_time" && \
  NO_PYTHON_MARKER="$BASE/python-was-invoked" PATH="$no_python_bin:$PATH" HOME="$FAKE_HOME" \
  "$BASH" "$SCRIPT" --specstory-path "$local_time_path" --format specstory --json) \
  >"$BASE/no-python-json-out" 2>"$BASE/no-python-json-err"
no_python_json_rc=$?
python3 -c 'import json,sys; json.load(open(sys.argv[1], encoding="utf-8"))' "$BASE/no-python-json-out"
no_python_json_valid=$?
if [ "$no_python_rc" = "0" ] && [ "$no_python_json_rc" = "0" ] && \
   [ "$no_python_json_valid" = "0" ] && [ ! -e "$BASE/python-was-invoked" ]; then
  pass "specstory-only TSV/JSON resolution does not invoke python3"
else
  fail "specstory-only TSV/JSON resolution does not invoke python3"
fi

# Claude JSONL validation conditionally requires Python and reports that
# dependency distinctly when a curated PATH omits it.
write_jsonl "$repo_local_time" "$UUID_D" >/dev/null
curated_bin="$BASE/no-python-path"
mkdir -p "$curated_bin"
for command_name in git grep iconv find sed basename dirname; do
  ln -s "$(command -v "$command_name")" "$curated_bin/$command_name"
done
(cd "$repo_local_time" && PATH="$curated_bin" HOME="$FAKE_HOME" \
  "$BASH" "$SCRIPT" --session-id "$UUID_D" --format claude) \
  >"$BASE/missing-python-out" 2>"$BASE/missing-python-err"
missing_python_rc=$?
missing_python_out="$(<"$BASE/missing-python-out")"
if [ "$missing_python_rc" = "6" ] && contains "$missing_python_out" $'status\tdependency_error'; then
  pass "Claude validation reports dedicated missing-python dependency status"
else
  fail "Claude validation reports dedicated missing-python dependency status"
fi

# A path outside the checkout can have a plausible header but is never accepted.
outside="$BASE/outside transcript.md"
printf '%s\n' "<!-- Claude Code Session $UUID_C (2026-08-28 08:00:00Z) -->" > "$outside"
run_find "$repo_dup/nested" --specstory-path "$outside" --format specstory
if [ "$LAST_RC" = "5" ] && contains "$LAST_OUT" $'status\tmismatch' && \
   ! contains "$LAST_OUT" "$outside" && ! contains "$LAST_ERR" "$outside" && \
   ! contains "$LAST_OUT" 'candidate'; then
  pass "outside explicit SpecStory selector fails without reflection"
else
  fail "outside explicit SpecStory selector fails without reflection"
fi

# Two worktrees get distinct repo roots, SpecStory directories, and Claude
# slugs even when the same UUID is present in both.
repo_wt="$(make_repo 'primary worktree')"
worktree="$BASE/secondary worktree"
git -C "$repo_wt" worktree add -q -b secondary "$worktree"
wt_one_transcript="$(write_transcript "$repo_wt" 'same-session.md' "$UUID_A")"
wt_two_transcript="$(write_transcript "$worktree" 'same-session.md' "$UUID_A")"
wt_one_jsonl="$(write_jsonl "$repo_wt" "$UUID_A")"
wt_two_jsonl="$(write_jsonl "$worktree" "$UUID_A")"
mkdir -p "$repo_wt/deep/path" "$worktree/deep/path"
run_find "$repo_wt/deep/path" --session-id "$UUID_A"
first_out="$LAST_OUT"; first_rc="$LAST_RC"
run_find "$worktree/deep/path" --session-id "$UUID_A"
second_out="$LAST_OUT"; second_rc="$LAST_RC"
if [ "$first_rc" = "0" ] && [ "$second_rc" = "0" ] && \
   contains "$first_out" "$wt_one_transcript" && contains "$first_out" "$wt_one_jsonl" && \
   contains "$second_out" "$wt_two_transcript" && contains "$second_out" "$wt_two_jsonl" && \
   ! contains "$first_out" "$wt_two_transcript" && ! contains "$second_out" "$wt_one_transcript"; then
  pass "two worktrees remain checkout-path isolated from subdirectories"
else
  fail "two worktrees remain checkout-path isolated from subdirectories"
fi

# A correctly named raw file with the wrong embedded cwd is a mismatch, not a hit.
repo_bad="$(make_repo 'json identity')"
write_transcript "$repo_bad" 'session.md' "$UUID_B" >/dev/null
bad_jsonl="$(write_jsonl "$repo_bad" "$UUID_B" "$repo_dup")"
run_find "$repo_bad" --session-id "$UUID_B"
if [ "$LAST_RC" = "5" ] && contains "$LAST_OUT" $'status\tmismatch' && contains "$LAST_OUT" "$bad_jsonl"; then
  pass "Claude JSONL requires exact embedded sessionId and git-root cwd"
else
  fail "Claude JSONL requires exact embedded sessionId and git-root cwd"
fi

# Sessions launched from a subdirectory live in that subdirectory's Claude
# project store. Exact UUID search must find it and canonicalize cwd to this root.
repo_subdir="$(make_repo 'subdirectory launched session')"
mkdir -p "$repo_subdir/apps/service" "$repo_subdir/caller/deep"
write_transcript "$repo_subdir" 'subdir-session.md' "$UUID_D" >/dev/null
subdir_jsonl="$(write_jsonl "$repo_subdir" "$UUID_D" "$repo_subdir/apps/service" "$repo_subdir/apps/service")"
run_find "$repo_subdir/caller/deep" --session-id "$UUID_D"
if [ "$LAST_RC" = "0" ] && contains "$LAST_OUT" "$subdir_jsonl"; then
  pass "exact UUID finds subdirectory-launched session by canonical worktree root"
else
  fail "exact UUID finds subdirectory-launched session by canonical worktree root"
fi

# A malformed complete/interior record invalidates the candidate even if a
# valid identity record appears first. An incomplete final write is tolerated.
repo_malformed="$(make_repo 'malformed jsonl')"
write_transcript "$repo_malformed" 'session.md' "$UUID_E" >/dev/null
malformed_jsonl="$(write_jsonl "$repo_malformed" "$UUID_E")"
printf '%s\n' '{malformed-complete-record}' >> "$malformed_jsonl"
run_find "$repo_malformed" --session-id "$UUID_E"
if [ "$LAST_RC" = "5" ] && contains "$LAST_ERR" 'malformed or incomplete; retry after the writer is quiescent'; then
  pass "malformed complete JSONL record fails exact validation"
else
  fail "malformed complete JSONL record fails exact validation"
fi

repo_partial="$(make_repo 'partial jsonl tail')"
write_transcript "$repo_partial" 'session.md' "$UUID_F" >/dev/null
partial_jsonl="$(write_jsonl "$repo_partial" "$UUID_F")"
printf '%s' '{"partial":' >> "$partial_jsonl"
run_find "$repo_partial" --session-id "$UUID_F"
if [ "$LAST_RC" = "5" ] && contains "$LAST_ERR" 'retry after the writer is quiescent'; then
  pass "unterminated final JSONL record fails closed"
else
  fail "unterminated final JSONL record fails closed"
fi

repo_false_tail="$(make_repo 'false bracket jsonl tail')"
write_transcript "$repo_false_tail" 'session.md' "$UUID_I" >/dev/null
false_jsonl="$(write_jsonl "$repo_false_tail" "$UUID_I")"
printf '%s' 'false]' >> "$false_jsonl"
run_find "$repo_false_tail" --session-id "$UUID_I"
if [ "$LAST_RC" = "5" ]; then
  pass "false-bracket final JSONL garbage fails closed"
else
  fail "false-bracket final JSONL garbage fails closed"
fi

repo_trailing="$(make_repo 'trailing json garbage')"
write_transcript "$repo_trailing" 'session.md' "$UUID_J" >/dev/null
trailing_jsonl="$(write_jsonl "$repo_trailing" "$UUID_J")"
printf '%s\n' '{"valid":true} trailing-garbage' >> "$trailing_jsonl"
run_find "$repo_trailing" --session-id "$UUID_J"
if [ "$LAST_RC" = "5" ]; then
  pass "trailing JSONL garbage fails closed"
else
  fail "trailing JSONL garbage fails closed"
fi

# One file cannot prove two worktrees. Conflicting canonical roots for the same
# session UUID make that candidate a mismatch even if one root is current.
repo_conflict="$(make_repo 'conflicting roots jsonl')"
other_conflict="$(make_repo 'other conflicting root')"
write_transcript "$repo_conflict" 'session.md' "$UUID_K" >/dev/null
conflict_jsonl="$(write_jsonl "$repo_conflict" "$UUID_K")"
python3 - "$conflict_jsonl" "$UUID_K" "$other_conflict" <<'PY'
import json
import sys
path, session_id, cwd = sys.argv[1:]
with open(path, "a", encoding="utf-8") as stream:
    stream.write(json.dumps({"sessionId": session_id, "cwd": cwd}) + "\n")
PY
run_find "$repo_conflict" --session-id "$UUID_K"
if [ "$LAST_RC" = "5" ] && contains "$LAST_ERR" 'conflicting canonical git roots'; then
  pass "one JSONL with two canonical worktree roots is rejected"
else
  fail "one JSONL with two canonical worktree roots is rejected"
fi

# Final-component symlinks are never exact artifacts, even when their targets
# contain otherwise-valid bytes.
repo_links="$(make_repo 'symlink rejection')"
outside_transcript="$BASE/real transcript target.md"
printf '%s\n' '<!-- Generated by SpecStory, Markdown v2.1.0 -->' '' \
  '# 2026-08-28 08:00:00Z' '' \
  "<!-- Claude Code Session $UUID_G (2026-08-28 08:00:00Z) -->" '' > "$outside_transcript"
mkdir -p "$repo_links/.specstory/history"
ln -s "$outside_transcript" "$repo_links/.specstory/history/link.md"
run_find "$repo_links" --specstory-path '.specstory/history/link.md' --format specstory
if [ "$LAST_RC" = "5" ] && contains "$LAST_ERR" 'must not be a symlink'; then
  pass "explicit SpecStory final symlink fails closed"
else
  fail "explicit SpecStory final symlink fails closed"
fi

repo_dirlink="$(make_repo 'specstory directory symlink')"
outside_history="$BASE/outside-history-root/history"
mkdir -p "$outside_history"
printf '%s\n' '<!-- Generated by SpecStory, Markdown v2.1.0 -->' '' \
  '# 2026-08-28 08:00:00Z' '' \
  "<!-- Claude Code Session $UUID_G (2026-08-28 08:00:00Z) -->" '' > "$outside_history/session.md"
ln -s "$BASE/outside-history-root" "$repo_dirlink/.specstory"
run_find "$repo_dirlink" --specstory-path '.specstory/history/session.md' --format specstory
if [ "$LAST_RC" = "5" ] && contains "$LAST_ERR" 'must be a canonical in-repository directory'; then
  pass "symlinked SpecStory root cannot escape the artifact root"
else
  fail "symlinked SpecStory root cannot escape the artifact root"
fi

raw_store="$FAKE_HOME/.claude/projects/$(project_slug "$repo_links")"
mkdir -p "$raw_store"
raw_target="$BASE/real-jsonl-target"
python3 - "$raw_target" "$UUID_G" "$repo_links" <<'PY'
import json
import sys
path, session_id, cwd = sys.argv[1:]
with open(path, "w", encoding="utf-8") as stream:
    stream.write(json.dumps({"sessionId": session_id, "cwd": cwd}) + "\n")
PY
ln -s "$raw_target" "$raw_store/$UUID_G.jsonl"
run_find "$repo_links" --session-id "$UUID_G" --format claude
if [ "$LAST_RC" = "5" ] && contains "$LAST_ERR" 'must not be symlinks'; then
  pass "exact raw JSONL final symlink fails closed"
else
  fail "exact raw JSONL final symlink fails closed"
fi

# Marker parsing is restricted to the fixed first two lines and direct children.
repo_header="$(make_repo 'fixed preamble')"
mkdir -p "$repo_header/.specstory/history/nested"
body_marker="$repo_header/.specstory/history/body-marker.md"
printf '%s\n' '<!-- Generated by SpecStory, Markdown v2.1.0 -->' '' \
  '# 2026-08-28 08:00:00Z' '' '<!-- not session metadata -->' '' \
  '_**User (2026-08-28 08:00:01Z)**_' '' \
  "<!-- Claude Code Session $UUID_H (2026-08-28 08:00:00Z) -->" > "$body_marker"
run_find "$repo_header" --specstory-path '.specstory/history/body-marker.md' --format specstory
body_rc="$LAST_RC"
nested_marker="$repo_header/.specstory/history/nested/session.md"
printf '%s\n' '<!-- Generated by SpecStory, Markdown v2.1.0 -->' '' \
  '# 2026-08-28 08:00:00Z' '' \
  "<!-- Claude Code Session $UUID_H (2026-08-28 08:00:00Z) -->" '' > "$nested_marker"
run_find "$repo_header" --specstory-path '.specstory/history/nested/session.md' --format specstory
if [ "$body_rc" = "5" ] && [ "$LAST_RC" = "5" ]; then
  pass "body markers and nested transcripts cannot satisfy exact preamble"
else
  fail "body markers and nested transcripts cannot satisfy exact preamble"
fi

# A control byte in a selected path must not create a TSV row or raw JSON byte.
control_name=$'control\trow.md'
write_transcript "$repo_header" "$control_name" "$UUID_H" >/dev/null
run_find "$repo_header" --specstory-path ".specstory/history/$control_name" --format specstory --json
json_safe=0
printf '%s' "$LAST_OUT" | python3 -c 'import json, sys; raw=sys.stdin.buffer.read(); json.loads(raw); assert all(byte >= 32 for byte in raw)' && json_safe=1
json_rc="$LAST_RC"
run_find "$repo_header" --specstory-path ".specstory/history/$control_name" --format specstory
if [ "$json_rc" = "5" ] && [ "$json_safe" = "1" ] && [ "$LAST_RC" = "5" ] && \
   [ "$(printf '%s\n' "$LAST_OUT" | wc -l | tr -d ' ')" = "6" ] && \
   ! contains "$LAST_OUT" 'candidate'; then
  pass "control-byte selector yields valid JSON and injection-safe TSV"
else
  fail "control-byte selector yields valid JSON and injection-safe TSV"
fi

# Filesystems can carry non-UTF-8 path bytes. Pass one directly through execve;
# neither stdout nor stderr may reflect it, and JSON must remain valid UTF-8.
python3 - "$repo_header" "$FAKE_HOME" "$SCRIPT" "$BASH" <<'PY'
import json
import os
import subprocess
import sys
repo, home, script, bash_path = sys.argv[1:]
raw_name = b"non-utf8-\xff.md"
env = os.environ.copy()
env["HOME"] = home
result = subprocess.run(
    [os.fsencode(bash_path), os.fsencode(script), b"--specstory-path", b".specstory/history/" + raw_name,
     b"--format", b"specstory", b"--json"],
    cwd=os.fsencode(repo), env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
)
stdout = result.stdout.decode("utf-8")
stderr = result.stderr.decode("utf-8")
json.loads(stdout)
assert b"\xff" not in result.stdout and b"\xff" not in result.stderr
assert "non-utf8" not in stdout and "non-utf8" not in stderr
sys.exit(0 if result.returncode == 5 else 1)
PY
non_utf8_rc=$?
if [ "$non_utf8_rc" = "0" ]; then
  pass "non-UTF-8 selector bytes are rejected with valid UTF-8 JSON"
else
  fail "non-UTF-8 selector bytes are rejected with valid UTF-8 JSON"
fi

# Canonical UUIDs are lowercase. Invalid selector bytes are never reflected.
upper_uuid='AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA'
run_find "$repo_header" --session-id "$upper_uuid" --format claude
if [ "$LAST_RC" = "1" ] && ! contains "$LAST_ERR" "$upper_uuid" && ! contains "$LAST_OUT" "$upper_uuid"; then
  pass "uppercase UUID is rejected without echoing the invalid selector"
else
  fail "uppercase UUID is rejected without echoing the invalid selector"
fi

# Header lookup must remain bounded by the two-line preamble even with a huge
# sparse tail. A whole-file scan would exceed this subprocess timeout.
repo_large="$(make_repo 'large transcript tail')"
large_path="$repo_large/.specstory/history/large.md"
mkdir -p "$(dirname "$large_path")"
python3 - "$large_path" "$UUID_H" <<'PY'
import sys
path, session_id = sys.argv[1:]
with open(path, "wb") as stream:
    stream.write(b"<!-- Generated by SpecStory, Markdown v2.1.0 -->\n\n")
    stream.write(b"# 2026-08-28 08:00:00Z\n\n")
    stream.write(f"<!-- Claude Code Session {session_id} (2026-08-28 08:00:00Z) -->\n\n".encode())
    stream.write(b"body-without-a-newline")
    stream.seek(512 * 1024 * 1024, 1)
    stream.write(b"x")
PY
python3 - "$repo_large" "$FAKE_HOME" "$SCRIPT" "$UUID_H" "$BASH" <<'PY'
import os
import subprocess
import sys
repo, home, script, session_id, bash_path = sys.argv[1:]
env = os.environ.copy()
env["HOME"] = home
result = subprocess.run(
    [bash_path, script, "--session-id", session_id, "--format", "specstory"],
    cwd=repo,
    env=env,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    timeout=2,
)
sys.exit(0 if result.returncode == 0 else 1)
PY
large_rc=$?
if [ "$large_rc" = "0" ]; then
  pass "large newline-free transcript tail uses a byte-bounded header read"
else
  fail "large newline-free transcript tail uses a byte-bounded header read"
fi

run_find "$repo" --session-id=
empty_session_rc="$LAST_RC"
run_find "$repo" --specstory-path=
empty_specstory_rc="$LAST_RC"
run_find "$repo" --session-id "$UUID_A" --format=
empty_format_rc="$LAST_RC"
run_find "$repo" --newest --session-id "$UUID_A"
mutual_rc="$LAST_RC"
if [ "$empty_session_rc" = "1" ] && [ "$empty_specstory_rc" = "1" ] && \
   [ "$empty_format_rc" = "1" ] && [ "$mutual_rc" = "1" ]; then
  pass "empty-valued selectors and exact/newest combination are invalid"
else
  fail "empty-valued selectors and exact/newest combination are invalid"
fi

run_find "$repo" --format both
if [ "$LAST_RC" = "1" ]; then pass "no selector is an argument error"
else fail "no selector is an argument error (got $LAST_RC)"; fi

printf 'pass: %d\nfail: %d\n' "$PASS_COUNT" "$FAIL_COUNT"
[ "$FAIL_COUNT" = "0" ]
