# PowerShell completion for pia. Generated by `pia completion powershell`.

$script:PiaCompletionDefaultSourceRoot = __PIA_DEFAULT_SOURCE_ROOT__

function Get-PiaCompletionComboId {
    param([string] $Engine)

    $root = if ($env:PIA_SOURCE_ROOT) { $env:PIA_SOURCE_ROOT } else { $script:PiaCompletionDefaultSourceRoot }
    foreach ($candidateEngine in @('pi', 'omp')) {
        if ($Engine -and $candidateEngine -ne $Engine) { continue }
        $engineRoot = Join-Path $root "combos/$candidateEngine"
        if (-not (Test-Path -LiteralPath $engineRoot -PathType Container)) { continue }
        foreach ($comboDir in @(Get-ChildItem -LiteralPath $engineRoot -Directory -ErrorAction SilentlyContinue | Sort-Object Name)) {
            if (($comboDir.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { continue }
            if ($comboDir.Name -notmatch '^[a-z0-9]([a-z0-9._-]{0,58}[a-z0-9_-])?$') { continue }
            $manifest = Get-Item -LiteralPath (Join-Path $comboDir.FullName 'combo.json') -ErrorAction SilentlyContinue
            $agentDir = Get-Item -LiteralPath (Join-Path $comboDir.FullName 'agent') -ErrorAction SilentlyContinue
            if (-not $manifest -or $manifest.PSIsContainer) { continue }
            if (($manifest.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { continue }
            if (-not $agentDir -or -not $agentDir.PSIsContainer) { continue }
            if (($agentDir.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { continue }
            "$candidateEngine/$($comboDir.Name)"
        }
    }
}

function ConvertTo-PiaCompletionResult {
    param(
        [Parameter(Mandatory)][string] $Value,
        [string] $Description = 'pia value',
        [System.Management.Automation.CompletionResultType] $Type = [System.Management.Automation.CompletionResultType]::ParameterValue
    )
    [System.Management.Automation.CompletionResult]::new($Value, $Value, $Type, $Description)
}

function Get-PiaCompletionValue {
    param(
        [string[]] $Values,
        [string] $Prefix,
        [string] $Description = 'pia value'
    )
    foreach ($value in $Values) {
        if ($value.StartsWith($Prefix, [StringComparison]::OrdinalIgnoreCase)) {
            ConvertTo-PiaCompletionResult -Value $value -Description $Description
        }
    }
}

function Get-PiaCompletionPositional {
    param([string[]] $Arguments)
    $skipValue = $false
    foreach ($argument in $Arguments) {
        if ($skipValue) {
            $skipValue = $false
            continue
        }
        switch -Regex ($argument) {
            '^--(description|session|goal|max-bytes)$' { $skipValue = $true; continue }
            '^--(description|session|goal|max-bytes)=' { continue }
            '^--' { continue }
            default { $argument }
        }
    }
}

function Get-PiaCompletionAstValue {
    param([System.Management.Automation.Language.CommandAst] $CommandAst)
    foreach ($element in $CommandAst.CommandElements) {
        if ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            [string] $element.Value
        } else {
            [string] $element.Extent.Text
        }
    }
}

Register-ArgumentCompleter -Native -CommandName pia -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $null = $cursorPosition
    $wordToComplete = [string] $wordToComplete

    $elements = @(Get-PiaCompletionAstValue -CommandAst $commandAst)
    $prior = @()
    if ($elements.Count -gt 1) { $prior = @($elements[1..($elements.Count - 1)]) }
    if ($wordToComplete -and $prior.Count -gt 0 -and $prior[-1] -eq $wordToComplete) {
        if ($prior.Count -gt 1) { $prior = @($prior[0..($prior.Count - 2)]) }
        else { $prior = @() }
    }

    $commands = [ordered]@{
        run = 'apply and launch a combo'
        use = 'save the default combo'
        current = 'print the selected combo'
        list = 'list available combos'
        derive = 'copy a combo and record its parent'
        lineage = 'inspect or acknowledge parent lineage'
        status = 'inspect managed runtime state'
        diff = 'compare runtime or parent state'
        apply = 'materialize combo runtime configuration'
        sessions = 'list sessions for a combo'
        fork = 'fork a same-engine session'
        handoff = 'create a cross-harness handoff'
        doctor = 'check the local pia toolchain'
        completion = 'print shell completion code'
        help = 'show help'
    }

    if ($prior.Count -eq 0) {
        foreach ($entry in $commands.GetEnumerator()) {
            if ($entry.Key.StartsWith($wordToComplete, [StringComparison]::OrdinalIgnoreCase)) {
                ConvertTo-PiaCompletionResult -Value $entry.Key -Description $entry.Value -Type Command
            }
        }
        Get-PiaCompletionValue -Values @('-h', '--help', '-V', '--version') -Prefix $wordToComplete -Description 'global option'
        return
    }

    $command = $prior[0]
    $arguments = @()
    if ($prior.Count -gt 1) { $arguments = @($prior[1..($prior.Count - 1)]) }
    if ($arguments -contains '--') {
        [System.Management.Automation.CompletionCompleters]::CompleteFilename($wordToComplete)
        return
    }
    if ($arguments.Count -gt 0 -and $arguments[-1] -eq '--session') {
        [System.Management.Automation.CompletionCompleters]::CompleteFilename($wordToComplete)
        return
    }
    if ($arguments.Count -gt 0 -and $arguments[-1] -in @('--description', '--goal', '--max-bytes')) { return }

    $positionals = @(Get-PiaCompletionPositional -Arguments $arguments)
    if ($wordToComplete.StartsWith('-')) {
        $options = switch ($command) {
            'list' { @('--tree', '--json') }
            'derive' { @('--description') }
            'lineage' { @('--ack', '--json') }
            { $_ -in @('status', 'sessions', 'doctor') } { @('--json') }
            'diff' { @('--runtime', '--parent', '--json') }
            'apply' { @('--dry-run', '--force', '--json') }
            'fork' { @('--session', '--latest') }
            'handoff' { @('--session', '--latest', '--goal', '--max-bytes', '--no-run') }
            default { @() }
        }
        $options = @($options | Where-Object { $arguments -notcontains $_ })
        Get-PiaCompletionValue -Values $options -Prefix $wordToComplete -Description "$command option"
        return
    }

    if ($command -in @('run', 'use', 'lineage', 'status', 'diff', 'apply', 'sessions')) {
        if ($positionals.Count -eq 0) {
            Get-PiaCompletionValue -Values @(Get-PiaCompletionComboId) -Prefix $wordToComplete -Description 'combo'
        }
        return
    }

    switch ($command) {
        'derive' {
            if ($positionals.Count -eq 0) {
                Get-PiaCompletionValue -Values @(Get-PiaCompletionComboId) -Prefix $wordToComplete -Description 'parent combo'
            }
        }
        'fork' {
            if ($positionals.Count -eq 0) {
                Get-PiaCompletionValue -Values @(Get-PiaCompletionComboId) -Prefix $wordToComplete -Description 'source combo'
            } elseif ($positionals.Count -eq 1) {
                $engine = ($positionals[0] -split '/', 2)[0]
                if ($engine -notin @('pi', 'omp')) { $engine = $null }
                Get-PiaCompletionValue -Values @(Get-PiaCompletionComboId -Engine $engine) -Prefix $wordToComplete -Description 'target combo'
            }
        }
        'handoff' {
            if ($positionals.Count -lt 2) {
                Get-PiaCompletionValue -Values @(Get-PiaCompletionComboId) -Prefix $wordToComplete -Description 'combo'
            }
        }
        'completion' {
            if ($positionals.Count -eq 0) {
                Get-PiaCompletionValue -Values @('zsh', 'bash', 'powershell') -Prefix $wordToComplete -Description 'shell'
            }
        }
    }
}
