# bash completion for pia. Generated by `pia completion bash`.
# macOS still ships Bash 3.2 without mapfile; every split candidate below is
# constrained to pia's whitespace-free command/flag/combo grammar.
# shellcheck disable=SC2207

_pia_combo_ids() {
    local wanted_engine="${1:-}" root engine manifest combo_dir name
    root="${PIA_SOURCE_ROOT:-}"
    [ -n "$root" ] || root=__PIA_DEFAULT_SOURCE_ROOT__

    for engine in pi omp; do
        [ -z "$wanted_engine" ] || [ "$engine" = "$wanted_engine" ] || continue
        for manifest in "$root"/combos/"$engine"/*/combo.json; do
            [ -f "$manifest" ] && [ ! -L "$manifest" ] || continue
            combo_dir="${manifest%/combo.json}"
            [ -d "$combo_dir" ] && [ ! -L "$combo_dir" ] || continue
            [ -d "$combo_dir/agent" ] && [ ! -L "$combo_dir/agent" ] || continue
            name="${combo_dir##*/}"
            [[ "$name" =~ ^[a-z0-9]([a-z0-9._-]{0,58}[a-z0-9_-])?$ ]] || continue
            printf '%s/%s\n' "$engine" "$name"
        done
    done
}

_pia_has_word() {
    local wanted="$1" word
    shift
    for word in "$@"; do
        [ "$word" = "$wanted" ] && return 0
    done
    return 1
}

_pia_options() {
    local option result=""
    for option in $1; do
        _pia_has_word "$option" "${COMP_WORDS[@]:2:$((COMP_CWORD - 2))}" || result="$result $option"
    done
    printf '%s\n' "$result"
}

_pia_collect_positionals() {
    PIA_POSITIONALS=()
    local index=2 word skip_value=0
    while [ "$index" -lt "$COMP_CWORD" ]; do
        word="${COMP_WORDS[$index]}"
        if [ "$skip_value" -eq 1 ]; then
            skip_value=0
        else
            case "$word" in
                --description|--session|--goal|--max-bytes) skip_value=1 ;;
                --description=*|--session=*|--goal=*|--max-bytes=*|--*) ;;
                *) PIA_POSITIONALS[${#PIA_POSITIONALS[@]}]="$word" ;;
            esac
        fi
        index=$((index + 1))
    done
}

_pia_complete_files() {
    if declare -F _filedir >/dev/null 2>&1; then
        _filedir
    else
        local IFS=$'\n'
        COMPREPLY=( $(compgen -f -- "$cur") )
    fi
}

_pia() {
    local cur prev command options engine separator_index index
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]:-}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W 'run use current list derive lineage status diff apply sessions fork handoff doctor completion help --help -h --version -V' -- "$cur") )
        return 0
    fi

    command="${COMP_WORDS[1]}"
    separator_index=0
    index=2
    while [ "$index" -lt "$COMP_CWORD" ]; do
        if [ "${COMP_WORDS[$index]}" = "--" ]; then separator_index="$index"; break; fi
        index=$((index + 1))
    done
    if [ "$separator_index" -ne 0 ]; then
        _pia_complete_files
        return 0
    fi

    case "$prev" in
        --session) _pia_complete_files; return 0 ;;
        --description|--goal|--max-bytes) return 0 ;;
    esac

    _pia_collect_positionals

    if [[ "$cur" == -* ]]; then
        case "$command" in
            list) options='--tree --json' ;;
            derive) options='--description' ;;
            lineage) options='--ack --json' ;;
            status|sessions|doctor) options='--json' ;;
            diff) options='--runtime --parent --json' ;;
            apply) options='--dry-run --force --json' ;;
            fork) options='--session --latest' ;;
            handoff) options='--session --latest --goal --max-bytes --no-run' ;;
            *) options='' ;;
        esac
        COMPREPLY=( $(compgen -W "$(_pia_options "$options")" -- "$cur") )
        return 0
    fi

    case "$command" in
        run|use|lineage|status|diff|apply|sessions)
            if [ "${#PIA_POSITIONALS[@]}" -eq 0 ]; then
                COMPREPLY=( $(compgen -W "$(_pia_combo_ids)" -- "$cur") )
            fi
            ;;
        derive)
            if [ "${#PIA_POSITIONALS[@]}" -eq 0 ]; then
                COMPREPLY=( $(compgen -W "$(_pia_combo_ids)" -- "$cur") )
            fi
            ;;
        fork)
            if [ "${#PIA_POSITIONALS[@]}" -eq 0 ]; then
                COMPREPLY=( $(compgen -W "$(_pia_combo_ids)" -- "$cur") )
            elif [ "${#PIA_POSITIONALS[@]}" -eq 1 ]; then
                engine="${PIA_POSITIONALS[0]%%/*}"
                COMPREPLY=( $(compgen -W "$(_pia_combo_ids "$engine")" -- "$cur") )
            fi
            ;;
        handoff)
            if [ "${#PIA_POSITIONALS[@]}" -lt 2 ]; then
                COMPREPLY=( $(compgen -W "$(_pia_combo_ids)" -- "$cur") )
            fi
            ;;
        completion)
            if [ "${#PIA_POSITIONALS[@]}" -eq 0 ]; then
                COMPREPLY=( $(compgen -W 'zsh bash powershell' -- "$cur") )
            fi
            ;;
    esac
}

complete -F _pia pia
