#compdef pia
# zsh completion for pia. Generated by `pia completion zsh`.

_pia_combo_values() {
  local wanted_engine="${1:-}" root engine manifest combo_dir name
  reply=()
  root="${PIA_SOURCE_ROOT:-}"
  [[ -n "$root" ]] || root=__PIA_DEFAULT_SOURCE_ROOT__

  for engine in pi omp; do
    [[ -z "$wanted_engine" || "$engine" == "$wanted_engine" ]] || continue
    for manifest in "$root"/combos/"$engine"/*/combo.json(N.); do
      [[ -f "$manifest" && ! -L "$manifest" ]] || continue
      combo_dir="${manifest:h}"
      [[ -d "$combo_dir" && ! -L "$combo_dir" ]] || continue
      [[ -d "$combo_dir/agent" && ! -L "$combo_dir/agent" ]] || continue
      name="${combo_dir:t}"
      [[ "$name" =~ '^[a-z0-9]([a-z0-9._-]{0,58}[a-z0-9_-])?$' ]] || continue
      reply+=("$engine/$name")
    done
  done
}

_pia_combo_ids() {
  # `_arguments` passes its own grouping flags (for example `-J -default-`)
  # to action functions. They are completion metadata, not an engine filter.
  _pia_combo_values
  _describe -t combos 'combo' reply
}

_pia_fork_targets() {
  local engine="${words[2]%%/*}"
  [[ "$engine" == pi || "$engine" == omp ]] || engine=""
  _pia_combo_values "$engine"
  _describe -t combos 'combo' reply
}

_pia() {
  local command separator
  local -a commands
  commands=(
    'run:apply and launch a combo'
    'use:save the default combo'
    'current:print the selected combo'
    'list:list available combos'
    'derive:copy a combo and record its parent'
    'lineage:inspect or acknowledge parent lineage'
    'status:inspect managed runtime state'
    'diff:compare runtime or parent state'
    'apply:materialize combo runtime configuration'
    'sessions:list sessions for a combo'
    'fork:fork a same-engine session'
    'handoff:create a cross-harness handoff'
    'doctor:check the local pia toolchain'
    'completion:print shell completion code'
    'help:show help'
  )

  if (( CURRENT == 2 )); then
    if [[ "$PREFIX" == -* ]]; then
      _values 'option' '-h[show help]' '--help[show help]' '-V[show version]' '--version[show version]'
    else
      _describe -t commands 'pia command' commands
    fi
    return
  fi

  command="$words[2]"
  separator=${words[(I)--]}
  if (( separator > 0 && CURRENT > separator )); then
    _default
    return
  fi

  words=("${words[@]:1}")
  (( CURRENT-- ))

  case "$command" in
    run)
      _arguments '1:combo:_pia_combo_ids' '--[pass remaining arguments to the harness]'
      ;;
    use)
      _arguments '1:combo:_pia_combo_ids'
      ;;
    current|help)
      _message 'no arguments'
      ;;
    list)
      _arguments '--tree[render the lineage tree]' '--json[emit JSON]'
      ;;
    derive)
      _arguments \
        '1:parent combo:_pia_combo_ids' \
        '2:new combo id:' \
        '--description=[set the child description]:description:'
      ;;
    lineage)
      _arguments '1:combo:_pia_combo_ids' '--ack[acknowledge the current parent digest]' '--json[emit JSON]'
      ;;
    status)
      _arguments '1:combo:_pia_combo_ids' '--json[emit JSON]'
      ;;
    diff)
      _arguments \
        '1:combo:_pia_combo_ids' \
        '(--parent)--runtime[compare source with managed runtime]' \
        '(--runtime)--parent[compare source with its parent]' \
        '--json[emit JSON]'
      ;;
    apply)
      _arguments \
        '1:combo:_pia_combo_ids' \
        '--dry-run[show actions without writing]' \
        '--force[replace conflicting runtime state]' \
        '--json[emit JSON]'
      ;;
    sessions)
      _arguments '1:combo:_pia_combo_ids' '--json[emit JSON]'
      ;;
    fork)
      _arguments \
        '1:source combo:_pia_combo_ids' \
        '2:target combo:_pia_fork_targets' \
        '(--latest)--session=[select a source session id or path]:session:_files' \
        '(--session)--latest[select the latest source session]' \
        '--[pass remaining arguments to the target harness]'
      ;;
    handoff)
      _arguments \
        '1:source combo:_pia_combo_ids' \
        '2:target combo:_pia_combo_ids' \
        '(--latest)--session=[select a source session id or path]:session:_files' \
        '(--session)--latest[select the latest source session]' \
        '--goal=[set the continuation goal]:goal:' \
        '--max-bytes=[limit handoff artifact bytes]:bytes:' \
        '--no-run[create the handoff without launching]' \
        '--[pass remaining arguments to the target harness]'
      ;;
    doctor)
      _arguments '--json[emit JSON]'
      ;;
    completion)
      _arguments '1:shell:(zsh bash powershell)'
      ;;
    *)
      _message 'unknown pia command'
      ;;
  esac
}

if [[ -n "${CURRENT:-}" ]]; then
  _pia "$@"
fi
